version: "3"
services:
  backend:
    container_name: s0backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 8080:8080
    depends_on:
      - python-service
      - mongo-db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  python-service:
    container_name: python-service
    build:
      dockerfile: ./backend/scripts/python-interface/Dockerfile
      context: ./backend/scripts/python-interface
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo-db:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
