---
name: ErrorRateByService
lookback: 15m
trigger:
  webhook:
    integration: alertmanager
    output:
      service: "job"
      alertname: "labels.alertname"
      span: "span_name"
    condition: "{{ if eq .TriggerProperties.alertname \"ErrorRateByService\" }}true{{ else }}false{{ end }}"
steps:
- displayName: Get ownership
  name: get_ownership
  integration: backstage
  function: get_properties_values
  input:
    filter: kind=component,metadata.name={{.TriggerProperties.service}}
  output:
    owner: "spec.owner"
    slack_channel: "metadata.labels.slack_channel"
- displayName: Get relevant logs
  name: get_relevant_logs
  integration: opensearch
  function: get_log_occurrences
  input:
    service: "{{.TriggerProperties.service}}"
    query: "{\"query\": {\"bool\": {\"must\": [{\"match\": {\"resource.service.name\": \"{{.TriggerProperties.service}}\"}},{\"range\": {\"@timestamp\": {\"gte\": \"{{date .TriggerProperties.timestamp \"-15m\" \"rfc\"}}\",\"lte\": \"{{date .TriggerProperties.timestamp \"+15m\" \"rfc\"}}\"}}}],\"must_not\": [{\"match\": {\"severity.text\": \"INFO\"}},{\"match\": {\"severity.text\": \"Information\"}}]}}}"
    compare_by: "body, resource.host.name"
  output:
    output_source: "output_source"
    count: "count"
    body: "body"
    hostname: "resource.host.name"
- displayName: Inspect traces
  name: inspect_traces
  integration: jaeger
  function: get_properties_values
  input:
    service: "{{.TriggerProperties.service}}"
    tags: "{\"error\":\"true\"}"
    query: "&start={{date .TriggerProperties.timestamp \"-0m\" \"ts\"}}&lookback=15m&maxDuration&minDuration"
    compare_by: "logs.exception.stacktrace, tags.grpc.error_message"
  output:
    output_source: "output_source"
    count: "count"
    log: "logs.exception.stacktrace, tags.grpc.error_message"
  condition: "{{if eq (len .AdditionalContext.opensearch_get_relevant_logs) 0}}true{{else}}false{{end}}"
- displayName: Compare traces
  name: compare_traces
  integration: jaeger
  function: compare_traces
  input:
    service: "{{.TriggerProperties.service}}"
    operation: "{{ default .TriggerProperties.span \"all\"}}"
    baseTraceTags: "{\"rpc.grpc.status_code\":\"0\"},{\"http.status_code\":\"200\"}"
    comparedTraceTags: "{\"error\":\"true\"}"
    baseTraceQuery: "&start={{date .TriggerProperties.timestamp \"-0m\" \"ts\"}}&lookback=30m&maxDuration&minDuration"
    comparedTraceQuery: "&start={{date .TriggerProperties.timestamp \"-0m\" \"ts\"}}&lookback=15m&maxDuration&minDuration"
  output:
    output_source: "output_source"
    operation: "operation"
    processes_diff: "processes"
    # TBD - 
    # spans_diff:
    # errors_diff:
    # duration_diff: 
- displayName: Get containers status
  name: get_containers_status
  integration: alertmanager
  function: get_relevant_alerts
  input:
    filter: "{{range .AdditionalContext.jaeger_compare_traces}}name={{.processes_diff.processName}},{{end}}"
  output:
    output_source: "output_source"
    alert: "alert"
- displayName: Summarize issue content
  name: summarize_issue_content
  integration: openai
  function: summarize_context
  input:
    context: "{{root}}"
  output:
    summary: "summary"
# - displayName: Send to slack channel
#   name: send_to_slack
#   integration: slack
#   function: post_message
#   input:
#     slack_channel: "{{range .AdditionalContext.backstage_get_ownership}}{{.slack_channel}},{{end}}"
#     parsable_context_object: "{{root}}"
#     post_message_payload: "{\"startedAt\": \"{{.TriggerProperties.timestamp}}\", \"service\": \"{{.TriggerProperties.service}}\", \"summary\": \"{{( index .AdditionalContext.openai_summarize-issue-content 0).summary}}\"}"

