---
name: ErrorRateByService
lookback: 15m
trigger:
  webhook:
    output:
      service: "job"
      span: "span_name"
      timestamp: "startsAt"
# Available data fields {service: string,span: string,timestamp: string}
steps:
- name: Get ownership
  integration: backstage1
  function: get_properties_values
  input:
    filter: kind=component,metadata.name={service}
  output:
    owner: "spec.owner"
    slack_channel: "metadata.labels.slack_channel"
# Available data fields {service: string,span: string,timestamp: string, additional_context: {
#     backstage1.get_properties_values.output: list[object]
#   }
# }
- name: Get relevant logs
  integration: opensearch_prod
  function: get_log_occurrences
  input:
    query: "{'query': {'bool': {'must': [{'match': {resource.name: {service}}},{'range': {timestamp: {'gte': {timestamp - 15m},'lte': {timestamp}}}}],'must_not': [{'match': {'severity.text': 'INFO'}},{'match': {'severity.text': 'Information'}}]}}}"
  output:
    count: "{sum}"
    body: "body"
    hostname: "resource.host.name"
# Available data fields {service: string,span: string,timestamp: string, additional_context: {
#     backstage1.get_properties_values.output: list[object],
#     opensearch_prod.get_log_occurrences.output: list[object]
#   }
# }
- name: Inspect traces
  integration: jaeger1
  function: get_properties_values
  input:
    service: "{service}"
    tags: "{'error': true}"
  output:
    count: sum()
    log: "logs:exception.stacktrace | tags:grpc.error_message"
  condition: empty(opensearch_prod.get_log_occurrences.output)
# Available data fields {service: string,span: string,timestamp: string, additional_context: {
#     backstage1.get_properties_values.output: list[object],
#     opensearch_prod.get_log_occurrences.output: list[object],
#     jaeger1.get_properties_values.output: list[object],
#   }
# }
- name: Correlate alerts
  integration: signal0ne
  function: correlate_ongoing_alerts
  input: 
    filter: timestamp>={timestamp - 15m}&timestamp<={timestamp + 15m}&semanticSimilarity=true
  output:
    alert: alert
# Available data fields {service: string,span: string,timestamp: string, additional_context: {
#     backstage1.get_properties_values.output: list[object],
#     opensearch_prod.get_log_occurrences.output: list[object],
#     jaeger1.get_properties_values.output: list[object],
#     
#   }, correlated_signals: {
#     alerts: alerts
#   }
# }
- name: Summarize context
  integration: openai
  function: summarize
  input:
    content_to_summarize: "{get_log_occurrences.output | get_properties_values.output}"
  output:
    summarization: content
# Available data fields {service: string,span: string,timestamp: string, additional_context: {
#     backstage1.get_properties_values.output: list[object],
#     opensearch_prod.get_log_occurrences.output: list[object],
#     jaeger1.get_properties_values.output: list[object],
#     openai.summarize.output: list[object]
#     
#   }, correlated_signals: {
#     alerts: alerts
#   }
# }
- name: Send to slack channel
  integration: slack
  function: post_message
  input:
    parsable_context_object: "."
    ignore_context_keys: "backstage1.get_properties_values.output[].slack_channel"
# Available data fields {service: string,span: string,timestamp: string, additional_context: {
#     backstage1.get_properties_values.output: list[object],
#     opensearch_prod.get_log_occurrences.output: list[object],
#     jaeger1.get_properties_values.output: list[object],
#     openai.summarize.output: list[object]
#     
#   }, correlated_signals: {
#     alerts: alerts
#   }
# }
