---
name: ErrorRateByService
lookback: 15m
trigger:
  webhook:
    output:
      service: "job"
      span: "span_name"
      timestamp: "startsAt"
steps:
- name: Get ownership
  integration: backstage_lab01
  function: get_properties_values
  input:
    filter: kind=component,metadata.name={{.TriggerProperties.service}}
  output:
    owner: "spec.owner"
    slack_channel: "metadata.labels.slack_channel"
- name: Compare traces
  integration: jaeger_prod
  function: compare_traces
  input:
    service: "{{.TriggerProperties.service}}"
    operation: "{{ default .TriggerProperties.span \"all\"}}"
    baseTraceTags: "{\"rpc.grpc.status_code\":\"0\"},{\"http.status_code\":\"200\"}"
    comparedTraceTags: "{\"error\":\"true\"}"
    baseTraceQuery: "&start={{date .TriggerProperties.timestamp \"-0m\" \"ts\"}}&lookback=30m&maxDuration&minDuration"
    comparedTraceQuery: "&start={{date .TriggerProperties.timestamp \"-0m\" \"ts\"}}&lookback=15m&maxDuration&minDuration"
  output:
    operation: "operation"
    processes_diff: "processes"
    # TBD - 
    # spans_diff:
    # errors_diff:
    # duration_diff: 

- name: Get containers status
  integration: alertmanager_prod
  function: get_relevant_alerts
  input:
    filter: "{{range .AdditionalContext.jaeger_prod_compare_traces.output}}name={{.processes_diff}},{{end}}"
  output:
    alert: "alert"

- name: Send to slack channel
  integration: slack_lab01
  function: post_message
  input:
    parsable_context_object: "{{index}}"
    ignore_context_keys: "backstage1.get_properties_values.output[].slack_channel"
    
    