---
name: ErrorRateByService
lookback: 15m
trigger:
  webhook:
    output:
      service: "job"
      span: "span_name"
      timestamp: "startsAt"
steps:
- name: Get ownership
  integration: backstage_lab01
  function: get_properties_values
  input:
    filter: kind=component,metadata.name={{.service}}
  output:
    owner: "spec.owner"
    slack_channel: "metadata.labels.slack_channel"
- name: Get relevant logs
  integration: opensearch_prod
  function: get_log_occurrences
  input:
    query: "{\"query\": {\"bool\": {\"must\": [{\"match\": {\"resource.service.name\": \"{{.service}}\"}},{\"range\": {\"@timestamp\": {\"gte\": \"{{date .timestamp \"-15m\" \"rfc\"}}\",\"lte\": \"{{date .timestamp \"+15m\" \"rfc\"}}\"}}}],\"must_not\": [{\"match\": {\"severity.text\": \"INFO\"}},{\"match\": {\"severity.text\": \"Information\"}}]}}}"
    compare_by: "body, resource.host.name"
  output:
    count: "count"
    body: "body"
    hostname: "resource.host.name"
- name: Inspect traces
  integration: jaeger_prod
  function: get_properties_values
  input:
    service: "{{.service}}"
    tags: "{\"error\": \"true\"}"
    query: "&start={{date .timestamp \"-0m\" \"ts\"}}&lookback=15m&maxDuration&minDuration"
    compare_by: "logs.exception.stacktrace, tags.grpc.error_message"
  output:
    count: "count"
    log: "logs.exception.stacktrace, tags.grpc.error_message"
  condition: "{{isempty .opensearch_prod.get_log_occurrences.output }}"
- name: Compare traces
  integration: jaeger_prod
  function: compare_traces
  input:
    service: "{{.service}}"
    operation: "{{ default .span \"all\"}}"
    baseTraceTags: "{\"rpc.grpc.status_code\": \"0\"},{\"http.status_code\":\"200\"}"
    comparedTraceTags: "{\"error\": \"true\"}"
    baseTraceQuery: "&start={{date .timestamp \"-0m\" \"ts\"}}&lookback=30m&maxDuration&minDuration"
    comparedTraceQuery: "&start={{date .timestamp \"-0m\" \"ts\"}}&lookback=15m&maxDuration&minDuration"
  output:
    operation: "operation"
    processes_diff: "processes"
    # TBD - 
    # spans_diff:
    # errors_diff:
    # duration_diff: 

# - name: Get containers status
#   integration: alertmanager_prod
#   function: get_relevant_alerts
#   input:    
#   output:

# - name: Correlate alerts
#   integration: signal0ne
#   function: correlate_ongoing_alerts
#   input: 
#     startTimestamp: "{{date .timestamp \"-15m\"}}"
#     endTimestamp: "{{date .timestamp \"+15m\"}}"
#     type: "semanticSimilarity"
#     compare_by: ".opensearch_prod.get_log_occurrences.output[].body, .jaeger_prod.get_properties_values.output[].log"
#   output:
#     alert: alert

- name: Send to slack channel
  integration: slack_lab01
  function: post_message
  input:
    parsable_context_object: "{{index}}"
    ignore_context_keys: "backstage1.get_properties_values.output[].slack_channel"
    
    